#ifndef CPPESPEAK_FILESYSTEM_GLOBAL_H
#define CPPESPEAK_FILESYSTEM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPPESPEAK_FILESYSTEM_LIBRARY)
#define CPPESPEAK_FILESYSTEM_EXPORT Q_DECL_EXPORT
#else
#define CPPESPEAK_FILESYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // CPPESPEAK_FILESYSTEM_GLOBAL_H
