#ifndef CPPESPEAK_OPTIONS_GLOBAL_H
#define CPPESPEAK_OPTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPPESPEAK_OPTIONS_LIBRARY)
#define CPPESPEAK_OPTIONS_EXPORT Q_DECL_EXPORT
#else
#define CPPESPEAK_OPTIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // CPPESPEAK_OPTIONS_GLOBAL_H
