#ifndef CPPESPEAK_ESPEAK_GLOBAL_H
#define CPPESPEAK_ESPEAK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CPPESPEAK_ESPEAK_LIBRARY)
#define CPPESPEAK_ESPEAK_EXPORT Q_DECL_EXPORT
#else
#define CPPESPEAK_ESPEAK_EXPORT Q_DECL_IMPORT
#endif

#endif // CPPESPEAK_ESPEAK_GLOBAL_H
